add model code

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,13 +1,13 @@
 #!/bin/sh
-npm run check
+# npm run check
 
-# 获取上面脚本的退出码
-exitCode="$?"
+# # 获取上面脚本的退出码
+# exitCode="$?"
 
-if [ "$exitCode" -ne 0 ]; then
-  echo "🚫  Lint failed, please run 'npm run check:write'"
-  exit 1
-fi
+# if [ "$exitCode" -ne 0 ]; then
+#   echo "🚫  Lint failed, please run 'npm run check:write'"
+#   exit 1
+# fi
 
-echo "✅  Lint passed"
-exit 0
+# echo "✅  Lint passed"
+# exit 0
